import axios from 'axios';
import { AIAnalysis } from '../models/Incident';

const GITHUB_API_BASE = 'https://api.github.com';

interface GitHubIssueResponse {
    html_url: string;
    number: number;
    id: number;
}

function buildIssueBody(
    analysis: AIAnalysis,
    endpoint: string,
    logs: string,
    commitDiff: string
): string {
    const logSnippet = logs.split('\n').slice(-10).join('\n');
    const diffSnippet = commitDiff.split('\n').slice(0, 30).join('\n');

    return `## 🚨 Incident Report — Auto-generated by AI SRE System

### 📍 Affected Endpoint
\`${endpoint}\`

---

### 🔍 Root Cause
${analysis.rootCause}

---

### 🛠 Suggested Fix
${analysis.suggestedFix}

---

### 🛡 Prevention Strategy
${analysis.preventionStrategy}

---

### 📊 Classification

| Field | Value |
|-------|-------|
| **Category** | ${analysis.category} |
| **Severity** | ${analysis.severity} |
| **AI Confidence** | ${analysis.confidence}% |

---

### 📋 Log Snippet (Last 10 Lines)
\`\`\`json
${logSnippet}
\`\`\`

---

### 📦 Recent Commit Diff
\`\`\`diff
${diffSnippet}
\`\`\`

---

*🤖 This issue was automatically created by the AI Incident Detection System*
*Timestamp: ${new Date().toISOString()}*`;
}

/**
 * Create a GitHub issue using the REST API
 */
export async function createGitHubIssue(
    analysis: AIAnalysis,
    endpoint: string,
    logs: string,
    commitDiff: string
): Promise<string> {
    const token = process.env.GITHUB_TOKEN;
    const owner = process.env.GITHUB_OWNER;
    const repo = process.env.GITHUB_REPO;

    if (!token || !owner || !repo ||
        token === 'your_github_token_here' ||
        owner === 'your_github_owner_here') {
        console.warn('⚠️  GitHub credentials not configured. Skipping issue creation.');
        return 'https://github.com/placeholder/issue/0';
    }

    const title = `[${analysis.severity}] API Failure - ${endpoint} (Confidence: ${analysis.confidence}%)`;
    const body = buildIssueBody(analysis, endpoint, logs, commitDiff);

    const labels = [
        'incident',
        'auto-generated',
        analysis.severity.toLowerCase(),
        analysis.category.toLowerCase().replace(' ', '-'),
    ];

    // Assignees: always include repo owner + any extra from GITHUB_ASSIGNEES env var.
    // GitHub will email every assignee automatically — no external email service needed.
    const assignees = Array.from(new Set([
        owner,
        ...(process.env.GITHUB_ASSIGNEES || '').split(',').map(a => a.trim()).filter(Boolean),
    ]));

    const response = await axios.post<GitHubIssueResponse>(
        `${GITHUB_API_BASE}/repos/${owner}/${repo}/issues`,
        {
            title,
            body,
            labels,
            assignees, // 👈 triggers GitHub's built-in email to all assignees
        },
        {
            headers: {
                Authorization: `Bearer ${token}`,
                Accept: 'application/vnd.github.v3+json',
                'X-GitHub-Api-Version': '2022-11-28',
            },
        }
    );

    console.log(`✅ GitHub issue #${response.data.number} created: ${response.data.html_url}`);
    return response.data.html_url;
}

/**
 * Close a GitHub issue when an incident is resolved.
 * Parses the issue number from the stored html_url.
 */
export async function closeGitHubIssue(githubIssueUrl: string): Promise<void> {
    const token = process.env.GITHUB_TOKEN;
    const owner = process.env.GITHUB_OWNER;
    const repo = process.env.GITHUB_REPO;

    if (!token || !owner || !repo ||
        token === 'your_github_token_here' ||
        githubIssueUrl.includes('placeholder')) {
        console.warn('⚠️  GitHub credentials not configured or placeholder URL — skipping issue close.');
        return;
    }

    // Extract issue number from URL: https://github.com/owner/repo/issues/42
    const match = githubIssueUrl.match(/\/issues\/(\d+)$/);
    if (!match) {
        console.warn('⚠️  Could not extract issue number from URL:', githubIssueUrl);
        return;
    }
    const issueNumber = match[1];

    const headers = {
        Authorization: `Bearer ${token}`,
        Accept: 'application/vnd.github.v3+json',
        'X-GitHub-Api-Version': '2022-11-28',
    };

    // Add a resolution comment then close the issue
    await axios.post(
        `${GITHUB_API_BASE}/repos/${owner}/${repo}/issues/${issueNumber}/comments`,
        { body: '✅ **Incident resolved** — this issue has been marked as resolved by the AI SRE System.' },
        { headers }
    );

    await axios.patch(
        `${GITHUB_API_BASE}/repos/${owner}/${repo}/issues/${issueNumber}`,
        { state: 'closed', state_reason: 'completed' },
        { headers }
    );

    console.log(`✅ GitHub issue #${issueNumber} closed: ${githubIssueUrl}`);
}
